---
openapi: 3.0.0
info:
  title: Account adjustment
  contact: {}
  version: "1.0"
servers:
  - url: http://127.0.0.1
paths:
  /dloan-transaction/v1/update-credit-limit:
    post:
      tags:
        - Account Adjustment
      summary: Credit Limit
      operationId: CreditLimit
      parameters:
        - name: x-request-id
          in: header
          description: Generated with RFC4122 standard.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-job-id
          in: header
          description: |-
            Generated by target service if blank, if not blank, use existing.
            Format: {XX}_{YYMMDD}{AAAAAAAA}{BB}{CCCCCC}
            22 Digits created based on combination of :
            - {XX} : Domain Number
            - {YYYYYY} : 6 digits of YYMMDD
            - {AAAAAAAA} : 8 characters, created from timestamp hashed with CRC32
                  Example : 2017-10-10T14:45:27.201131865+07:00  -> 958fd1cb
            - {BB} : 2 digits of Domain Code (01)
            - {CCCCCC} : 6 digits of secure random (067492)
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-real-ip
          in: header
          description: IP of caller
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 127.0.0.1
        - name: x-caller-service
          in: header
          description: Caller Service
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: FrontEnd
        - name: x-caller-domain
          in: header
          description: Caller Domain
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: Front
        - name: datetime
          in: header
          description: Date and time of request
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 2019-07-04T00:00:00+07:00
        - name: accept
          in: header
          description: Example “application/json”
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: application/json
        - name: accept-language
          in: header
          description: Accept language (e.g en/th)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: accept-encoding
          in: header
          description: Character encoding (UTF-8)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-device
          in: header
          description: Client Device
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-application
          in: header
          description: Application that sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-channel
          in: header
          description: Channel used to sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: user-agent
          in: header
          description: Browser agent/mobile/etc (HTTP standard header)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: original-caller-domain
          in: header
          description: Original caller domain
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int32
            example: 88
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditLimitRequest'
            example:
              rq_body:
                account_number: "600007700001"
                credit_limit: 9000
                user_id: kbank
                service_branch: 2
                terminal_id: 1
                comment: update-credit-limit
        required: true
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAdjustmentSuccess'
              example:
                rs_body: {}
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAdjustmentFailed1'
              example:
                errors:
                  - error_code: E88020511
                    error_type: BUSINESS
                    error_desc: Effective date must be equal to system date
      deprecated: false
  /dloan-payment/v1/accounts/payment-condition:
    post:
      tags:
        - Account Adjustment
      summary: Auto Deduct
      operationId: AutoDeduct
      parameters:
        - name: x-request-id
          in: header
          description: Generated with RFC4122 standard.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-job-id
          in: header
          description: |-
            Generated by target service if blank, if not blank, use existing.
            Format: {XX}_{YYMMDD}{AAAAAAAA}{BB}{CCCCCC}
            22 Digits created based on combination of :
            - {XX} : Domain Number
            - {YYYYYY} : 6 digits of YYMMDD
            - {AAAAAAAA} : 8 characters, created from timestamp hashed with CRC32
                  Example : 2017-10-10T14:45:27.201131865+07:00  -> 958fd1cb
            - {BB} : 2 digits of Domain Code (01)
            - {CCCCCC} : 6 digits of secure random (067492)
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-real-ip
          in: header
          description: IP of caller
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 127.0.0.1
        - name: x-caller-service
          in: header
          description: Caller Service
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: FrontEnd
        - name: x-caller-domain
          in: header
          description: Caller Domain
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: Front
        - name: datetime
          in: header
          description: Date and time of request
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 2019-07-04T00:00:00+07:00
        - name: accept
          in: header
          description: Example “application/json”
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: application/json
        - name: accept-language
          in: header
          description: Accept language (e.g en/th)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: accept-encoding
          in: header
          description: Character encoding (UTF-8)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-device
          in: header
          description: Client Device
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-application
          in: header
          description: Application that sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-channel
          in: header
          description: Channel used to sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: user-agent
          in: header
          description: Browser agent/mobile/etc (HTTP standard header)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: original-caller-domain
          in: header
          description: Original caller domain
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int32
            example: 88
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutoDeductRequest'
            example:
              rq_body:
                account_number: "600007700001"
                payment_condition:
                  deduction_account: "600007700001"
                user_id: kbank
                service_branch: 2
                terminal_id: 1
                comment: payment-condition
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAdjustmentSuccess'
              example:
                rs_body: {}
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAdjustmentFailed1'
              example:
                errors:
                  - error_code: E88020511
                    error_type: BUSINESS
                    error_desc: Effective date must be equal to system date
      deprecated: false
  /dloan-interest/v1/sub-accounts/update-interest-rate:
    post:
      tags:
        - Account Adjustment
      summary: Interest Rate
      operationId: InterestRate
      parameters:
        - name: x-request-id
          in: header
          description: Generated with RFC4122 standard.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-job-id
          in: header
          description: |-
            Generated by target service if blank, if not blank, use existing.
            Format: {XX}_{YYMMDD}{AAAAAAAA}{BB}{CCCCCC}
            22 Digits created based on combination of :
            - {XX} : Domain Number
            - {YYYYYY} : 6 digits of YYMMDD
            - {AAAAAAAA} : 8 characters, created from timestamp hashed with CRC32
                  Example : 2017-10-10T14:45:27.201131865+07:00  -> 958fd1cb
            - {BB} : 2 digits of Domain Code (01)
            - {CCCCCC} : 6 digits of secure random (067492)
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-real-ip
          in: header
          description: IP of caller
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 127.0.0.1
        - name: x-caller-service
          in: header
          description: Caller Service
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: FrontEnd
        - name: x-caller-domain
          in: header
          description: Caller Domain
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: Front
        - name: datetime
          in: header
          description: Date and time of request
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 2019-07-04T00:00:00+07:00
        - name: accept
          in: header
          description: Example “application/json”
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: application/json
        - name: accept-language
          in: header
          description: Accept language (e.g en/th)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: accept-encoding
          in: header
          description: Character encoding (UTF-8)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-device
          in: header
          description: Client Device
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-application
          in: header
          description: Application that sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-channel
          in: header
          description: Channel used to sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: user-agent
          in: header
          description: Browser agent/mobile/etc (HTTP standard header)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: original-caller-domain
          in: header
          description: Original caller domain
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int32
            example: 88
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InterestRateRequest'
            example:
              rq_body:
                account_number: 600007700001
                account_sequence: 1
                interest_index: MRR
                interest_spread: 3
                effective_date: 01-01-2019
                user_id: kbank
                service_branch: 2
                terminal_id: 1
                comment: update-interest-rate
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAdjustmentSuccess'
              example:
                rs_body: {}
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAdjustmentFailed1'
              example:
                errors:
                  - error_code: E88020511
                    error_type: BUSINESS
                    error_desc: Effective date must be equal to system date
      deprecated: false
  /dloan-payment/v1/update-installment-and-payment-term:
    post:
      tags:
        - Account Adjustment
      summary: Installment & Payment Term
      operationId: Installment&PaymentTerm
      parameters:
        - name: x-request-id
          in: header
          description: Generated with RFC4122 standard.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-job-id
          in: header
          description: |-
            Generated by target service if blank, if not blank, use existing.
            Format: {XX}_{YYMMDD}{AAAAAAAA}{BB}{CCCCCC}
            22 Digits created based on combination of :
            - {XX} : Domain Number
            - {YYYYYY} : 6 digits of YYMMDD
            - {AAAAAAAA} : 8 characters, created from timestamp hashed with CRC32
                  Example : 2017-10-10T14:45:27.201131865+07:00  -> 958fd1cb
            - {BB} : 2 digits of Domain Code (01)
            - {CCCCCC} : 6 digits of secure random (067492)
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-real-ip
          in: header
          description: IP of caller
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 127.0.0.1
        - name: x-caller-service
          in: header
          description: Caller Service
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: FrontEnd
        - name: x-caller-domain
          in: header
          description: Caller Domain
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: Front
        - name: datetime
          in: header
          description: Date and time of request
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 2019-07-04T00:00:00+07:00
        - name: accept
          in: header
          description: Example “application/json”
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: application/json
        - name: accept-language
          in: header
          description: Accept language (e.g en/th)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: accept-encoding
          in: header
          description: Character encoding (UTF-8)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-device
          in: header
          description: Client Device
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-application
          in: header
          description: Application that sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-channel
          in: header
          description: Channel used to sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: user-agent
          in: header
          description: Browser agent/mobile/etc (HTTP standard header)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: original-caller-domain
          in: header
          description: Original caller domain
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int32
            example: 88
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstallmentandPaymentTermRequest'
            example:
              rq_body:
                account_number: 600007700001
                account_sequence: 1
                installment_amount: 5000
                number_of_payment: 12
                user_id: kbank
                service_branch: 2
                terminal_id: 1
                comment: update-installment-and-payment-term
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAdjustmentSuccess'
              example:
                rs_body: {}
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountAdjustmentFailed1'
              example:
                errors:
                  - error_code: E88020511
                    error_type: BUSINESS
                    error_desc: Effective date must be equal to system date
      deprecated: false
components:
  schemas:
    Identity:
      title: Identity
      required:
        - userRoles
      type: object
      properties:
        userRoles:
          type: array
          items:
            type: string
    CreditLimitRequest:
      title: CreditLimitRequest
      required:
        - rq_body
      type: object
      properties:
        rq_body:
          $ref: '#/components/schemas/AccountAdjustmentRqBody'
    AccountAdjustmentRqBody:
      title: AccountAdjustmentRqBody
      required:
        - account_number
        - credit_limit
        - service_branch
        - terminal_id
        - user_id
      type: object
      properties:
        account_number:
          type: number
          description: Loan account number
        credit_limit:
          type: number
          description: Credit limit of the account, used to indicate the maximum amount allowed to be disbursed from the account
        user_id:
          type: string
          description: ID of user who update credit limit
        service_branch:
          type: number
          description: Branch where credit limit is updated
        terminal_id:
          type: string
          description: Terminal location
        comment:
          type: string
          description: Comment
    AccountAdjustmentSuccess:
      title: AccountAdjustmentSuccess
      required:
        - rs_body
      type: object
      properties:
        rs_body:
          type: object
    Error:
      title: Error
      required:
        - error_code
        - error_desc
        - error_type
      type: object
      properties:
        error_code:
          type: string
          description: Error code
        error_type:
          type: string
          description: Type of error
        error_desc:
          type: string
          description: Error description
    AccountAdjustmentFailed1:
      title: AccountAdjustmentFailed1
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    AutoDeductRequest:
      title: AutoDeductRequest
      required:
        - rq_body
      type: object
      properties:
        rq_body:
          $ref: '#/components/schemas/AccountAdjustmentRqBody1'
    AccountAdjustmentRqBody1:
      title: AccountAdjustmentRqBody1
      required:
        - account_number
        - payment_condition
        - service_branch
        - terminal_id
        - user_id
      type: object
      properties:
        account_number:
          type: string
        payment_condition:
          $ref: '#/components/schemas/PaymentCondition'
        user_id:
          type: string
          description: ID of user who update credit limit
        service_branch:
          type: integer
          description: Branch where credit limit is updated
          format: int32
        terminal_id:
          type: integer
          description: Terminal location
          format: int32
        comment:
          type: string
          description: Comment
    PaymentCondition:
      title: PaymentCondition
      required:
        - deduction_account
      type: object
      properties:
        deduction_account:
          type: string
    InterestRateRequest:
      title: InterestRateRequest
      required:
        - rq_body
      type: object
      properties:
        rq_body:
          $ref: '#/components/schemas/AccountAdjustmentRqBody2'
    AccountAdjustmentRqBody2:
      title: AccountAdjustmentRqBody2
      required:
        - account_number
        - account_sequence
        - effective_date
        - interest_index
        - interest_spread
        - service_branch
        - terminal_id
        - user_id
      type: object
      properties:
        account_number:
          type: integer
          description: Loan account number
          format: int64
        account_sequence:
          type: integer
          description: Loan account item
          format: int32
        interest_index:
          type: string
          description: A benchmark to calculate the interest rate that is charged on financial products
        interest_spread:
          type: integer
          description: A profit margin to bank, which is the difference between the interest rate a bank pays to depositors and the interest rate it receives from loans to consumers
          format: int32
        effective_date:
          type: string
          description: Effective date. Display in format "YYYY-MM-DD"
        user_id:
          type: string
          description: ID of user who update credit limit
        service_branch:
          type: integer
          description: Branch where credit limit is updated
          format: int32
        terminal_id:
          type: integer
          description: Terminal location
          format: int32
        comment:
          type: string
          description: Comment
    InstallmentandPaymentTermRequest:
      title: InstallmentandPaymentTermRequest
      required:
        - rq_body
      type: object
      properties:
        rq_body:
          $ref: '#/components/schemas/AccountAdjustmentRqBody3'
    AccountAdjustmentRqBody3:
      title: AccountAdjustmentRqBody3
      required:
        - account_number
        - account_sequence
        - installment_amount
        - number_of_payment
        - service_branch
        - terminal_id
        - user_id
      type: object
      properties:
        account_number:
          type: integer
          description: Loan account number
          format: int64
        account_sequence:
          type: integer
          description: Loan account item
          format: int32
        installment_amount:
          type: number
          description: Amount of money expected to be paid in each time period
        number_of_payment:
          type: integer
          description: The number of time period that customer have to repay for this item
          format: int32
        user_id:
          type: string
          description: ID of user who update credit limit
        service_branch:
          type: integer
          description: Branch where credit limit is updated
          format: int32
        terminal_id:
          type: integer
          description: Terminal location
          format: int32
        comment:
          type: string
          description: Comment
