---
openapi: 3.0.0
info:
  title: Open New Account
  description: Create loan account
  contact: {}
  version: "1.0"
servers:
  - url: https://127.0.0.1
paths:
  /dloan-account-mgmt/v1/accounts:
    post:
      tags:
        - Open New Account
      summary: Create loan account
      operationId: Createloanaccount
      parameters:
        - name: x-request-id
          in: header
          description: Generated with RFC4122 standard.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-job-id
          in: header
          description: |-
            Generated by target service if blank, if not blank, use existing.
            Format: {XX}_{YYMMDD}{AAAAAAAA}{BB}{CCCCCC}
            22 Digits created based on combination of :
            - {XX} : Domain Number
            - {YYYYYY} : 6 digits of YYMMDD
            - {AAAAAAAA} : 8 characters, created from timestamp hashed with CRC32
                  Example : 2017-10-10T14:45:27.201131865+07:00  -> 958fd1cb
            - {BB} : 2 digits of Domain Code (01)
            - {CCCCCC} : 6 digits of secure random (067492)
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-real-ip
          in: header
          description: IP of caller
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 127.0.0.1
        - name: x-caller-service
          in: header
          description: Caller Service
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: FrontEnd
        - name: x-caller-domain
          in: header
          description: Caller Domain
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: Front
        - name: datetime
          in: header
          description: Date and time of request
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 2019-07-04T00:00:00+07:00
        - name: accept
          in: header
          description: Example “application/json”
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: application/json
        - name: accept-language
          in: header
          description: Accept language (e.g en/th)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: accept-encoding
          in: header
          description: Character encoding (UTF-8)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-device
          in: header
          description: Client Device
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-application
          in: header
          description: Application that sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-channel
          in: header
          description: Channel used to sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: user-agent
          in: header
          description: Browser agent/mobile/etc (HTTP standard header)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: original-caller-domain
          in: header
          description: Original caller domain
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int32
            example: 88
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateloanaccountRequest'
            example:
              rq_body:
                customer_number: "111111111111"
                customer_type: 450
                account_name: นางสาวน้ำหนึ่ง ใจดี
                account_name_en: Miss Namneung Jaidee
                credit_limit: 350000
                credit_term_number: 12
                credit_term_unit: M
                product_name: "7200120090005"
                disbursement_account: "20000002020"
                account_branch: 1
                response_unit: 1
                application_id: APP0001
                payment:
                  payment_frequency: 1
                  payment_unit: M
                  payment_date: 31
                  payment_calculation_method: installment
                interest:
                  interest_index: FIXED
                  interest_spread: 19
                user_id: xxx1
                service_branch: 1
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenAccount_Success'
              example:
                rs_body:
                  account_number: "600007700001"
                  open_date: 01-02-2021
        "404":
          description: Not Found
          content:
            text/plain:
              schema:
                type: string
                example: 404 page not found
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenAccount_Failed'
              example:
                errors:
                  - error_code: E88020511
                    error_type: BUSINESS
                    error_desc: Effective date must be equal to system date
                    error_detail: Effective date must be equal to system date
      deprecated: false
components:
  schemas:
    Fnx-Header:
      title: Fnx-Header
      required:
        - identity
      type: object
      properties:
        identity:
          $ref: '#/components/schemas/Identity'
    Identity:
      title: Identity
      required:
        - userRoles
      type: object
      properties:
        userRoles:
          type: array
          items:
            type: string
    CreateloanaccountRequest:
      title: CreateloanaccountRequest
      required:
        - rq_body
      type: object
      properties:
        rq_body:
          $ref: '#/components/schemas/OpenAccountRqBody'
    OpenAccountRqBody:
      title: OpenAccountRqBody
      required:
        - account_branch
        - account_name
        - account_name_en
        - application_id
        - credit_limit
        - credit_term_number
        - credit_term_unit
        - customer_number
        - customer_type
        - deduction_account
        - disbursement_account
        - interest
        - payment
        - product_name
        - response_unit
        - service_branch
        - user_id
      type: object
      properties:
        customer_number:
          type: string
          description: Customer number of account owner
        customer_type:
          type: string
          description: Customer type of account owner, used to classify the type of customer in business aspect
        account_name:
          type: string
          description: Account name in first-tongue language
        account_name_en:
          type: string
          description: Account name in English
        credit_limit:
          type: integer
          description: Credit limit of the account, used to indicate the maximum amount allowed to be disbursed from the account
          format: int32
        credit_term_number:
          type: integer
          description: Credit term number of the account,  used to indicate the number of time period that customer have to repay
          format: int32
        credit_term_unit:
          type: string
          description: Credit term unit of the account, used to indicate the time period unit. Display in abbreviation e.g. M (month), W (week)
        product_name:
          type: string
          description: Product name of the account
        deduction_account:
          type: string
          description: Linked deposit account number where money is transferred from when performing repayment transaction
        disbursement_account:
          type: string
          description: Linked deposit account number where money is transferred from when performing repayment transaction
        account_branch:
          type: integer
          description: Branch of ownership
          format: int32
        response_unit:
          type: integer
          description: Response Unit
          format: int32
        application_id:
          type: string
          description: ID of application who perform transaction
        payment:
          $ref: '#/components/schemas/Payment'
        interest:
          $ref: '#/components/schemas/Interest'
        user_id:
          type: string
          description: ID of user who create the loan account
        service_branch:
          type: integer
          description: Branch where account is created
          format: int32
    Payment:
      title: Payment
      required:
        - payment_calculation_method
        - payment_date
        - payment_frequency
        - payment_unit
      type: object
      properties:
        payment_frequency:
          type: integer
          description: Frequency of repayment
          format: int32
        payment_unit:
          type: string
          description: Time period unit of repayment. Display in abbreviation e.g. M (month), W (week)
        payment_date:
          type: integer
          description: Specified date in month to perform repayment transaction
          format: int32
        payment_calculation_method:
          type: string
          description: Name of method used to calculate payment
        max_installment_amount:
          type: integer
          description: The maximum installment amount allowed in each time period unit for the account
          format: int32
      description: Payment information
    Interest:
      title: Interest
      required:
        - interest_index
        - interest_spread
      type: object
      properties:
        interest_index:
          type: string
          description: A benchmark to calculate the interest rate that is charged on financial products
        interest_spread:
          type: number
          description: A profit margin to bank, which is the difference between the interest rate a bank pays to depositors and the interest rate it receives from loans to consumers
          format: int32
      description: Interest information
    OpenAccount_Success:
      title: OpenAccount_Success
      required:
        - rs_body
      type: object
      properties:
        rs_body:
          $ref: '#/components/schemas/OpenAccountRsBody'
    OpenAccountRsBody:
      title: OpenAccountRsBody
      required:
        - account_number
        - open_date
      type: object
      properties:
        account_number:
          type: string
          description: Loan account number
        open_date:
          type: string
          description: Opened date of the account. Display in format "YYYY-MM-DD"
    OpenAccount_Failed:
      title: OpenAccount_Failed
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    Error:
      title: Error
      required:
        - error_code
        - error_desc
        - error_detail
        - error_type
      type: object
      properties:
        error_code:
          type: string
          description: List of errors
        error_type:
          type: string
          description: Error code
        error_desc:
          type: string
          description: Type of error
        error_detail:
          type: string
          description: Error description
