---
openapi: 3.0.0
info:
  title: Account Inquiry
  description: |-
    - Calculate Installment Amount
    - Inquire Loan Account Details
    - Inquire Loan Item Details
    - Inquire Loan Account Financial Activity
  contact: {}
  version: "1.0"
servers:
- url: https://127.0.0.1
- url: http://127.0.0.1/aggregation/v1/accounts/{account_number}/{transaction_sequence}/{transaction_date_from}
  variables:
    account_number:
      default: DefaultParameterValue
    transaction_sequence:
      default: DefaultParameterValue
    transaction_date_from:
      default: DefaultParameterValue
tags:
- name: Misc
paths:
  /dloan-transaction-mgmt/v1/product/calculate-installment-amount:
    post:
      tags:
      - Misc
      summary: Calculate Installment Amount
      description: Calculate Installment Amount
      operationId: CalculateInstallmentAmount
      parameters:
      - name: x-job-id
        in: header
        description: |-
          Unique reference ID from the original caller application. This reference will be passed through all activities to indicate the same business event.
          For financial transaction and database updated transaction, this reference will be checked for duplication.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 2558f7e5-afa6-4171-851c-6853ecdb1d85
      - name: x-real-ip
        in: header
        description: IP of caller
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 127.0.0.1
      - name: x-caller-service
        in: header
        description: Caller Service
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: FrontEnd
      - name: x-caller-domain
        in: header
        description: Caller Domain
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Front
      - name: x-device
        in: header
        description: Client Device
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-application
        in: header
        description: Application that sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-channel
        in: header
        description: Channel used to sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: user-agent
        in: header
        description: Browser agent/mobile/etc (HTTP standard header)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: datetime
        in: header
        description: Date and time of request
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: '"2021-03-15T02:59:23+07:00"'
      - name: accept
        in: header
        description: Example “application/json”
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: accept-language
        in: header
        description: Accept language (e.g en/th)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: accept-encoding
        in: header
        description: Character encoding (UTF-8)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: original-caller-domain
        in: header
        description: Original caller domain
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
          example: 88
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculateInstallmentAmountRequest'
            example:
              rq_body:
                disbursement_amount: 40000
                number_of_payment: 10
                interest_rate: 18
                payment_frequency: 1
                payment_unit: M
                product_name: "7200120090001"
        required: true
      responses:
        "400":
          content:
            text/html; charset=utf-8:
              schema:
                $ref: '#/components/schemas/CalculateInstallmentAmountError1'
              example:
                errors:
                - error_code: E88020503
                  error_type: BUSINESS
                  error_desc: Account number does not exist
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalculateInstallmentAmountSuccess'
              example:
                rs_body:
                  installment_amount: 4337.37
      deprecated: false
      servers:
      - url: https://127.0.0.1
  /dloan-account/v1/accounts/{account_number}:
    post:
      tags:
      - Misc
      summary: Account Details
      description: Account Details
      operationId: AccountDetails
      parameters:
      - name: x-job-id
        in: header
        description: |-
          Unique reference ID from the original caller application. This reference will be passed through all activities to indicate the same business event.
          For financial transaction and database updated transaction, this reference will be checked for duplication.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 2558f7e5-afa6-4171-851c-6853ecdb1d85
      - name: x-real-ip
        in: header
        description: IP of caller
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 127.0.0.1
      - name: x-caller-service
        in: header
        description: Caller Service
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: FrontEnd
      - name: x-caller-domain
        in: header
        description: Caller Domain
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Front
      - name: x-device
        in: header
        description: Client Device
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-application
        in: header
        description: Application that sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-channel
        in: header
        description: Channel used to sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: user-agent
        in: header
        description: Browser agent/mobile/etc (HTTP standard header)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: datetime
        in: header
        description: Date and time of request
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: '"2021-03-15T02:59:23+07:00"'
      - name: accept
        in: header
        description: Example “application/json”
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: accept-language
        in: header
        description: Accept language (e.g en/th)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: accept-encoding
        in: header
        description: Character encoding (UTF-8)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: original-caller-domain
        in: header
        description: Original caller domain
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
          example: 88
      - name: account_number
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDetailsRequest'
            example:
              rq_body: {}
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanItemDetailsSuccess'
              example:
                rs_body:
                  account_number: 610000000016
                  product_name: "7200120090001"
                  customer_number: "12111111111"
                  customer_type: 450
                  account_name: นางสาวกานดา มาดี
                  account_name_en: Miss Kanda Madee
                  currency: THB
                  account_branch: 1
                  credit_term_number: 12
                  credit_term_unit: M
                  disbursement_account: "20000002010"
                  open_date: 2019-08-19T00:00:00.000+0000
                  application_id: APP0001
                  closed_date: 2030-10-31T00:00:00.000+0000
                  limit:
                    credit_limit: 100000
                    balance: 100000
                    available_balance: 0
                    maturity_date: 2020-08-19T00:00:00.000+0000
                    is_freeze: false
                    available_bal_increase_option: percentage
                    minimum_credit_limit: 0
                    maximum_credit_limit: 100000
                    repaid_principal_percentage: 50
                  payment:
                    payment_frequency: 1
                    payment_unit: M
                    payment_date: 31
                    payment_calculation_method: installment
                    billing_offset_day: 1
                    deduction_account: "20000002010"
                    minimum_principal_payment_amount: 0
                    minimum_principal_payment_percentage: 0
                    last_installment_bill_option: balloon-amount
                    max_installment_amount: 50000
                  interest:
                    interest_index: MRR
                    interest_spread: 12
                    interest_rate: 19.12
                    interest_max_index: MAX
                    interest_max_rate: 28
                    penalty_index: pen
                    penalty_rate: 28
                    grace_day: 5
                    oldest_stmt_due_date: 2019-07-31T00:00:00.000+0000
                    grace_end_date: 2019-08-05T00:00:00.000+0000
                    is_start_penalty: true
                    catch_up_method: 0
                    unpaid_accrued_interest_amount: 1519.9
                    unpaid_accrued_penalty_amount: 720.61
                  bills:
                    total_unpaid_penalty_amount: 720.61
                    total_unpaid_interest_amount: 1519.9
                    total_unpaid_principal_amount: 2259.49
                    total_bill_unpaid_amount: 4500
                    total_balance_due: 4500
                    minimum_payment_due: 4500
                  installment_bills:
                    unpaid_penalty_amount: 720.61
                    unpaid_interest_amount: 1519.9
                    unpaid_principal_amount: 2259.49
                    total_bill_unpaid_amount: 4500
                  minimum_payment_bills:
                    unpaid_penalty_amount: 111.11
                    unpaid_interest_amount: 222.22
                    unpaid_principal_amount: 33333.33
                    minimum_payment_due: 33666.66
                    principal_due: 120000
                    full_payment_due: 120333.33
        "400":
          content:
            text/html; charset=utf-8:
              schema:
                $ref: '#/components/schemas/CalculateInstallmentAmountError3'
              example:
                errors:
                - error_code: E88020503
                  error_type: BUSINESS
                  error_desc: Account number does not exist
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/CalculateInstallmentAmountError1'
      deprecated: false
      servers:
      - url: https://127.0.0.1
  /dloan-account/v1/items/{account_number}/{account_sequence}:
    post:
      tags:
      - Misc
      summary: Loan Item Details
      description: Loan Item Details
      operationId: LoanItemDetails
      parameters:
      - name: x-job-id
        in: header
        description: |-
          Unique reference ID from the original caller application. This reference will be passed through all activities to indicate the same business event.
          For financial transaction and database updated transaction, this reference will be checked for duplication.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 2558f7e5-afa6-4171-851c-6853ecdb1d85
      - name: x-real-ip
        in: header
        description: IP of caller
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 127.0.0.1
      - name: x-caller-service
        in: header
        description: Caller Service
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: FrontEnd
      - name: x-caller-domain
        in: header
        description: Caller Domain
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Front
      - name: x-device
        in: header
        description: Client Device
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-application
        in: header
        description: Application that sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-channel
        in: header
        description: Channel used to sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: user-agent
        in: header
        description: Browser agent/mobile/etc (HTTP standard header)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: datetime
        in: header
        description: Date and time of request
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: '"2021-03-15T02:59:23+07:00"'
      - name: accept
        in: header
        description: Example “application/json”
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: accept-language
        in: header
        description: Accept language (e.g en/th)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: accept-encoding
        in: header
        description: Character encoding (UTF-8)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: original-caller-domain
        in: header
        description: Original caller domain
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
          example: 88
      - name: account_number
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: account_sequence
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanItemDetailsRequest'
            example:
              rq_body: {}
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanItemDetailsSuccess'
              example:
                rs_body:
                  account_number: 610000000016
                  account_sequence: 1
                  product_name: "7200120090001"
                  customer_type: 450
                  account_branch: 1
                  open_date: 2019-08-19T00:00:00.000+0000
                  is_closed: true
                  closed_date: 2030-10-31T00:00:00.000+0000
                  limit:
                    balance: 100000
                    currency: THB
                  bills:
                    unpaid_penalty_amount: 720.61
                    unpaid_interest_amount: 1519.9
                    unpaid_principal_amount: 2259.49
                    total_bill_unpaid_amount: 4500
                    total_balance_due: 4500
                    minimum_payment_due: 4500
                  installment_bills:
                    unpaid_penalty_amount: 720.61
                    unpaid_interest_amount: 1519.9
                    unpaid_principal_amount: 2259.49
                    total_bill_unpaid_amount: 4500
                  minimum_payment_bills:
                    unpaid_penalty_amount: 111.11
                    unpaid_interest_amount: 222.22
                    unpaid_principal_amount: 33333.33
                    minimum_payment_due: 33666.66
                    principal_due: 120000
                    full_payment_due: 120333.33
                  payment:
                    payment_frequency: 1
                    payment_unit: M
                    payment_date: 31
                    payment_calculation_method: installment
                    billing_offset_day: 1
                    installment_amount: 5000
                    next_bill_cutoff_date: 2019-10-31T00:00:00.000+0000
                    number_of_payment: 12
                    first_payment_date: 2019-10-01T00:00:00.000+0000
                    minimum_principal_payment_amount: 0
                    minimum_principal_payment_percentage: 0
                    last_installment_bill_option: balloon-amount
                  interest:
                    interest_index: MRR
                    interest_spread: 12
                    interest_rate: 19.12
                    interest_max_index: MAX
                    interest_max_rate: 28
                    penalty_index: pen
                    grace_day: 5
                    catch_up_method: 0
                    unpaid_accrued_interest_amount: 1519.9
                    unpaid_accrued_penalty_amount: 720.61
                    is_start_penalty: true
                  statement:
                    oldest_stmt_due_date: 2019-10-01T00:00:00.000+0000
                    oldest_stmt_due_bill_amount: 5000
        "400":
          content:
            text/html; charset=utf-8:
              schema:
                $ref: '#/components/schemas/CalculateInstallmentAmountError3'
              example:
                errors:
                - error_code: E88020503
                  error_type: BUSINESS
                  error_desc: Account number does not exist
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/CalculateInstallmentAmountError3'
      deprecated: false
      servers:
      - url: https://127.0.0.1
  /{transaction_date_to}:
    post:
      tags:
      - Misc
      summary: Loan Account Activity
      description: Loan Account Activity
      operationId: LoanAccountActivity
      parameters:
      - name: limit
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 50
      - name: x-job-id
        in: header
        description: |-
          Unique reference ID from the original caller application. This reference will be passed through all activities to indicate the same business event.
          For financial transaction and database updated transaction, this reference will be checked for duplication.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 2558f7e5-afa6-4171-851c-6853ecdb1d85
      - name: x-real-ip
        in: header
        description: IP of caller
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 127.0.0.1
      - name: x-caller-service
        in: header
        description: Caller Service
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: FrontEnd
      - name: x-caller-domain
        in: header
        description: Caller Domain
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Front
      - name: x-device
        in: header
        description: Client Device
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-application
        in: header
        description: Application that sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-channel
        in: header
        description: Channel used to sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: user-agent
        in: header
        description: Browser agent/mobile/etc (HTTP standard header)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: datetime
        in: header
        description: Date and time of request
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: '"2021-03-15T02:59:23+07:00"'
      - name: accept
        in: header
        description: Example “application/json”
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: accept-language
        in: header
        description: Accept language (e.g en/th)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: accept-encoding
        in: header
        description: Character encoding (UTF-8)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: original-caller-domain
        in: header
        description: Original caller domain
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int32
          example: 88
      - name: transaction_date_to
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanAccountActivityRequest'
            example:
              rq_body: {}
        required: true
      responses:
        "400":
          content:
            text/html; charset=utf-8:
              schema:
                $ref: '#/components/schemas/LoanItemDetailsError3'
              example:
                errors:
                - error_code: E88020503
                  error_type: BUSINESS
                  error_desc: Account number does not exist
                  error_detail: 'Account number does not exist, Caused by: Could not read item Class: acct_bk ID: {"acctGroup":3,"acctNbr":"600113113111"}, Caused by: recordnot found'
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/CalculateInstallmentAmountError3'
              example:
                errors:
                - error_code: E88020503
                  error_type: BUSINESS
                  error_desc: Account number does not exist
                  error_detail: 'Account number does not exist, Caused by: Could not read item Class: acct_bk ID: {"acctGroup":3,"acctNbr":"600113113111"}, Caused by: recordnot found'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoanAccountActivitySuccess'
              example:
                rs_body:
                  transactions:
                  - transaction_sequence: 1
                    transaction_date: 2021-01-31T00:00:00.000+0000
                    transaction_time: 54625
                    transaction_code: disbursement
                    transaction_description: disbursement
                    original_transaction_date: 2021-01-25T00:00:00.000+0000
                    transaction_amount: 10000
                    end_balance: 10000
                    user_id: TNC00001
                    service_branch: 900
                    job_id: 7a44b7ba-9f27-485f-b419-25b91f3eaf9d
                    disbursement:
                      account_sequence: 1
                      installment_amount: 10000
                      first_payment_date: 2021-01-31T00:00:00.000+0000
                      number_of_payment: 3
                      interest_index: MRR
                      interest_spread: 3
                      interest_rate: 12.12345
                      related_account: 167772809
                      original_job_id: 7a44b7ba-9f27-485f-b419-25b91f3eaf9d
                      original_transaction_sequence: 1
                    repayment:
                      principal_amount: 9000
                      interest_amount: 800
                      penalty_amount: 200
                      related_account: 167772809
                      original_job_id: 7a44b7ba-9f27-485f-b419-25b91f3eaf9d
      deprecated: false
      servers:
      - url: http://127.0.0.1/aggregation/v1/accounts/{account_number}/{transaction_sequence}/{transaction_date_from}
        variables:
          account_number:
            default: DefaultParameterValue
          transaction_sequence:
            default: DefaultParameterValue
          transaction_date_from:
            default: DefaultParameterValue
components:
  schemas:
    CalculateInstallmentAmountRequest:
      title: CalculateInstallmentAmountRequest
      required:
      - rq_body
      type: object
      properties:
        rq_body:
          $ref: '#/components/schemas/RqBody'
    RqBody:
      title: RqBody
      required:
      - disbursement_amount
      - interest_rate
      - number_of_payment
      - payment_frequency
      - payment_unit
      - product_name
      type: object
      properties:
        disbursement_amount:
          type: number
          description: Disbursement amount
        number_of_payment:
          type: integer
          description: The number of time period that customer have to repay for this item
          format: int32
        interest_rate:
          type: number
          description: Rate used to calculation interest amount
        payment_frequency:
          type: integer
          description: Frequency of invoice period
          format: int32
        payment_unit:
          type: string
          description: Time unit of invoice period. Display in abbreviation e.g. M (month), W (week)
        product_name:
          type: string
          description: Product name of the account for determining buffer rate and installment rounding digit
    Error:
      title: Error
      required:
      - error_code
      - error_desc
      - error_type
      type: object
      properties:
        error_code:
          type: string
          description: Error code
        error_type:
          type: string
          description: Type of error
        error_desc:
          type: string
          description: Error description
    CalculateInstallmentAmountError1:
      title: CalculateInstallmentAmountError1
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          description: List of errors
          items:
            $ref: '#/components/schemas/Error'
    CalculateInstallmentAmountSuccess:
      title: CalculateInstallmentAmountSuccess
      required:
      - rs_body
      type: object
      properties:
        rs_body:
          $ref: '#/components/schemas/RsBody'
    RsBody:
      title: RsBody
      required:
      - installment_amount
      type: object
      properties:
        installment_amount:
          type: number
    AccountDetailsRequest:
      title: AccountDetailsRequest
      required:
      - rq_body
      type: object
      properties:
        rq_body:
          type: object
    CalculateInstallmentAmountSuccess1:
      title: CalculateInstallmentAmountSuccess1
      required:
      - rq_body
      type: object
      properties:
        rq_body:
          $ref: '#/components/schemas/RqBody1'
    RqBody1:
      title: RqBody1
      required:
      - installment_amount
      type: object
      properties:
        installment_amount:
          type: number
    Error2:
      title: Error2
      required:
      - error_code
      - error_desc
      - error_type
      type: object
      properties:
        error_code:
          type: string
          description: Error code
        error_type:
          type: string
          description: Type of error
        error_desc:
          type: string
          description: Error description
    CalculateInstallmentAmountError3:
      title: CalculateInstallmentAmountError3
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          description: List of errors
          items:
            $ref: '#/components/schemas/Error2'
    LoanItemDetailsSuccess:
      title: LoanItemDetailsSuccess
      required:
      - rs_body
      type: object
      properties:
        rs_body:
          $ref: '#/components/schemas/RsBody1'
    RsBody1:
      title: RsBody1
      required:
      - account_branch
      - account_number
      - account_sequence
      - bills
      - closed_date
      - customer_type
      - installment_bills
      - interest
      - is_closed
      - limit
      - minimum_payment_bills
      - open_date
      - payment
      - product_name
      - statement
      type: object
      properties:
        account_number:
          type: integer
          description: Loan account number
          format: int64
        account_sequence:
          type: integer
          description: Loan account item
          format: int32
        product_name:
          type: string
          description: Product name of the account
        customer_type:
          type: string
          description: Customer type of account owner, used to classify the type of customer in business aspect
        account_branch:
          type: integer
          description: Branch of ownership
          format: int32
        open_date:
          type: string
          description: Opened date of the item. Display in format "YYYY-MM-DD"
        is_closed:
          type: boolean
          description: Flag to indicate where the item is closed
        closed_date:
          type: string
          description: Closed date of the item. Display in format "YYYY-MM-DD"
        limit:
          $ref: '#/components/schemas/Limit'
        bills:
          $ref: '#/components/schemas/Bills'
        installment_bills:
          $ref: '#/components/schemas/InstallmentBills'
        minimum_payment_bills:
          $ref: '#/components/schemas/MinimumPaymentBills'
        payment:
          $ref: '#/components/schemas/Payment'
        interest:
          $ref: '#/components/schemas/Interest'
        statement:
          $ref: '#/components/schemas/Statement'
    Limit:
      title: Limit
      required:
      - balance
      - currency
      type: object
      properties:
        balance:
          type: integer
          description: Loan balance of the item
          format: int32
        currency:
          type: string
          description: Currency used for the account
      description: Limitation of item
    Bills:
      title: Bills
      required:
      - minimum_payment_due
      - total_balance_due
      - total_bill_unpaid_amount
      - unpaid_interest_amount
      - unpaid_penalty_amount
      - unpaid_principal_amount
      type: object
      properties:
        unpaid_penalty_amount:
          type: number
          description: Total unpaid penalty amount of the item in all bills
        unpaid_interest_amount:
          type: number
          description: Total unpaid interest amount of the item in all bills
        unpaid_principal_amount:
          type: number
          description: Total unpaid principal amount of the item in all bills
        total_bill_unpaid_amount:
          type: integer
          description: Total unpaid amount of the item in all bills
          format: int32
        total_balance_due:
          type: integer
          description: Total unpaid balance of the item in all bills
          format: int32
        minimum_payment_due:
          type: integer
          description: Total minimum payment due of the item in all bills
          format: int32
      description: Bill element of the item
    InstallmentBills:
      title: InstallmentBills
      required:
      - total_bill_unpaid_amount
      - unpaid_interest_amount
      - unpaid_penalty_amount
      - unpaid_principal_amount
      type: object
      properties:
        unpaid_penalty_amount:
          type: number
          description: Unpaid penalty amount of the item in all installment bills
        unpaid_interest_amount:
          type: number
          description: Unpaid interest amount of the item in all installment bills
        unpaid_principal_amount:
          type: number
          description: Unpaid principal amount of the item in all installment bills
        total_bill_unpaid_amount:
          type: integer
          description: Total unpaid amount of the item in all installment bills
          format: int32
      description: Installment bill element of the item
    MinimumPaymentBills:
      title: MinimumPaymentBills
      required:
      - full_payment_due
      - minimum_payment_due
      - principal_due
      - unpaid_interest_amount
      - unpaid_penalty_amount
      - unpaid_principal_amount
      type: object
      properties:
        unpaid_penalty_amount:
          type: number
          description: Unpaid penalty amount of the item in all minimum bills
        unpaid_interest_amount:
          type: number
          description: Unpaid interest amount of the item in all minimum bills
        unpaid_principal_amount:
          type: number
          description: Unpaid principal amount of the item in all minimum bills
        minimum_payment_due:
          type: number
          description: Minimum payment due of the item in all minimum bills
        principal_due:
          type: integer
          description: Unpaid principal of the item in all minimum bills
          format: int32
        full_payment_due:
          type: number
          description: Full payment due of the item in all minimum bills
      description: Minimum payment bill element of the item
    Payment:
      title: Payment
      required:
      - billing_offset_day
      - first_payment_date
      - installment_amount
      - last_installment_bill_option
      - minimum_principal_payment_amount
      - minimum_principal_payment_percentage
      - next_bill_cutoff_date
      - number_of_payment
      - payment_calculation_method
      - payment_date
      - payment_frequency
      - payment_unit
      type: object
      properties:
        payment_frequency:
          type: integer
          description: Frequency of invoice period
          format: int32
        payment_unit:
          type: string
          description: Time unit of invoice period. Display in abbreviation e.g. M (month), W (week)
        payment_date:
          type: integer
          description: Specified date in month to perform repayment transaction
          format: int32
        payment_calculation_method:
          type: string
          description: Name of method used to calculate payment
        billing_offset_day:
          type: integer
          description: Number of days between cut off date and bill generation date
          format: int32
        installment_amount:
          type: number
          description: Amount of money expected to be paid in each time period
        next_bill_cutoff_date:
          type: string
          description: Cutoff date of the next bill
        number_of_payment:
          type: integer
          description: The number of time period that customer have to repay for this item
          format: int32
        first_payment_date:
          type: string
          description: The first date to perform repayment transaction. Display in format "YYYY-MM-DD"
        minimum_principal_payment_amount:
          type: integer
          description: Principal amount paid, used if payment_calculation_method is minimum
          format: int32
        minimum_principal_payment_percentage:
          type: integer
          description: Principal percentage paid, used if payment_calculation_method is minimum
          format: int32
        last_installment_bill_option:
          type: string
          description: Method used to calculate last bill if payment_calculation_method is installment
      description: Payment information
    Interest:
      title: Interest
      required:
      - catch_up_method
      - grace_day
      - interest_index
      - interest_max_index
      - interest_max_rate
      - interest_rate
      - interest_spread
      - is_start_penalty
      - penalty_index
      - unpaid_accrued_interest_amount
      - unpaid_accrued_penalty_amount
      type: object
      properties:
        interest_index:
          type: string
          description: A benchmark to calculate the interest rate that is charged on financial products
        interest_spread:
          type: integer
          description: A profit margin to bank, which is the difference between the interest rate a bank pays to depositors and the interest rate it receives from loans to consumers
          format: int32
        interest_rate:
          type: number
          description: Rate used to calculation interest amount
        interest_max_index:
          type: string
          description: A max benchmark to calculate the interest rate that is charged on financial products
        interest_max_rate:
          type: integer
          description: Maximum interest rate allowed
          format: int32
        penalty_index:
          type: string
          description: A benchmark to calculate the penalty rate that is charged on financial products
        grace_day:
          type: integer
          description: Number of days between bill generation date and penalty start date
          format: int32
        catch_up_method:
          type: integer
          description: Method used to calculate penalty amount that occurred in grace period (The period between bill generation date and penalty start date) 0 = No catch up 1 = Catch up by including due date 2 = Catch up by excluding due date
          format: int32
        unpaid_accrued_interest_amount:
          type: number
          description: Total current unpaid accrued interest amount of the item
        unpaid_accrued_penalty_amount:
          type: number
          description: Total current unpaid accrued penalty amount of the item
        is_start_penalty:
          type: boolean
          description: Flag to indicate whether the item already started calculate penalty
      description: Interest information
    Statement:
      title: Statement
      required:
      - oldest_stmt_due_bill_amount
      - oldest_stmt_due_date
      type: object
      properties:
        oldest_stmt_due_date:
          type: string
          description: The oldest due date of unpaid statement of the item
        oldest_stmt_due_bill_amount:
          type: number
          description: The amount of the oldest unpaid statement of the item
      description: Statement information
    RsBody2:
      title: RsBody2
      required:
      - account_branch
      - account_name
      - account_name_en
      - account_number
      - application_id
      - bills
      - closed_date
      - credit_term_number
      - credit_term_unit
      - currency
      - customer_number
      - customer_type
      - disbursement_account
      - installment_bills
      - interest
      - limit
      - minimum_payment_bills
      - open_date
      - payment
      - product_name
      type: object
      properties:
        account_number:
          type: integer
          description: Loan account number
          format: int64
        product_name:
          type: string
          description: Product name of the account
        customer_number:
          type: string
          description: Customer number of account owner
        customer_type:
          type: string
          description: Customer type of account owner, used to classify the type of customer in business aspect
        account_name:
          type: string
          description: Account name in first-tongue language
        account_name_en:
          type: string
          description: Account name in English
        currency:
          type: string
          description: Currency used for the account
        account_branch:
          type: integer
          description: Branch of ownership
          format: int32
        credit_term_number:
          type: integer
          description: Credit term number of the account,  used to indicate the number of time period that valid for customer
          format: int32
        credit_term_unit:
          type: string
          description: Credit term unit of the account, used to indicate the time period unit that valid for customer. Display in abbreviation e.g. M (month), W (week)
        disbursement_account:
          type: string
          description: Linked deposit account number where loan is transferred to when performing disbursement transaction
        open_date:
          type: string
          description: Opened date of the account. Display in format "YYYY-MM-DD"
        application_id:
          type: string
          description: ID of application who perform transaction
        closed_date:
          type: string
          description: Closed date of the account
        limit:
          $ref: '#/components/schemas/Limit1'
        payment:
          $ref: '#/components/schemas/Payment1'
        interest:
          $ref: '#/components/schemas/Interest1'
        bills:
          $ref: '#/components/schemas/Bills1'
        installment_bills:
          $ref: '#/components/schemas/InstallmentBills1'
        minimum_payment_bills:
          $ref: '#/components/schemas/MinimumPaymentBills1'
    Limit1:
      title: Limit1
      required:
      - available_bal_increase_option
      - available_balance
      - balance
      - credit_limit
      - is_freeze
      - maturity_date
      - maximum_credit_limit
      - minimum_credit_limit
      - repaid_principal_percentage
      type: object
      properties:
        credit_limit:
          type: number
          description: Credit limit of the account, used to indicate the maximum amount allowed to be disbursed from the account
        balance:
          type: number
          description: Loan balance of the account
        available_balance:
          type: number
          description: Available balance left that allowed to disburse
        maturity_date:
          type: string
          description: Account maturity date
        is_freeze:
          type: boolean
          description: Flag to indicate whether some financial transactions are not allowed to process
        available_bal_increase_option:
          type: string
          description: Method used to indicate when to start increasing available balance
        minimum_credit_limit:
          type: number
          description: Minimum credit limit of the account, used to indicate the minimum amount allowed to be disbursed from the account
        maximum_credit_limit:
          type: number
          description: Maximum credit limit of the account, used to indicate the maximum amount allowed to be disbursed from the account
        repaid_principal_percentage:
          type: integer
          description: Percentage of principal repaid to start increasing available balance
          format: int32
      description: Limitation of account
    Payment1:
      title: Payment1
      required:
      - billing_offset_day
      - deduction_account
      - last_installment_bill_option
      - max_installment_amount
      - minimum_principal_payment_amount
      - minimum_principal_payment_percentage
      - payment_calculation_method
      - payment_date
      - payment_frequency
      - payment_unit
      type: object
      properties:
        payment_frequency:
          type: integer
          description: Payment information
          format: int32
        payment_unit:
          type: string
          description: Frequency of invoice period
        payment_date:
          type: integer
          description: Time unit of invoice period. Display in abbreviation e.g. M (month), W (week)
          format: int32
        payment_calculation_method:
          type: string
          description: Specified date in month to perform repayment transaction
        billing_offset_day:
          type: integer
          description: Name of method used to calculate payment
          format: int32
        deduction_account:
          type: string
          description: Number of days between cut off date and bill generation date
        minimum_principal_payment_amount:
          type: number
          description: Linked deposit account number where money is transferred from when performing repayment transaction
        minimum_principal_payment_percentage:
          type: number
          description: Principal amount paid, used if payment_calculation_method is minimum
        last_installment_bill_option:
          type: string
          description: Method used to calculate last bill if payment_calculation_method is installment
        max_installment_amount:
          type: number
          description: The maximum installment amount allowed in each time period unit for the account
    Interest1:
      title: Interest1
      required:
      - catch_up_method
      - grace_day
      - grace_end_date
      - interest_index
      - interest_max_index
      - interest_max_rate
      - interest_rate
      - interest_spread
      - is_start_penalty
      - oldest_stmt_due_date
      - penalty_index
      - penalty_rate
      - unpaid_accrued_interest_amount
      - unpaid_accrued_penalty_amount
      type: object
      properties:
        interest_index:
          type: string
          description: A benchmark to calculate the interest rate that is charged on financial products
        interest_spread:
          type: number
          description: A profit margin to bank, which is the difference between the interest rate a bank pays to depositors and the interest rate it receives from loans to consumers
        interest_rate:
          type: number
          description: Rate used to calculation interest amount
        interest_max_index:
          type: string
          description: A max benchmark to calculate the interest rate that is charged on financial products
        interest_max_rate:
          type: number
          description: Maximum interest rate allowed
        penalty_index:
          type: string
          description: A benchmark to calculate the penalty rate that is charged on financial products
        penalty_rate:
          type: number
          description: Rate used to calculation penalty amount
        grace_day:
          type: integer
          description: Number of days between bill generation date and penalty start date
          format: int32
        oldest_stmt_due_date:
          type: string
          description: The oldest due date of unpaid statement of all items under the account
        grace_end_date:
          type: string
          description: The last day before starting calculate penalty
        is_start_penalty:
          type: boolean
          description: Flag to indicate whether the account already started calculate penalty
        catch_up_method:
          type: integer
          description: Method used to calculate penalty amount that occurred in grace period (The period between bill generation date and penalty start date) 0 = No catch up 1 = Catch up by including due date 2 = Catch up by excluding due date
          format: int32
        unpaid_accrued_interest_amount:
          type: number
          description: Total current unpaid accrued interest amount of all items under the account
        unpaid_accrued_penalty_amount:
          type: number
          description: Total current unpaid accrued penalty amount of all items under the account
      description: Interest information
    Bills1:
      title: Bills1
      required:
      - minimum_payment_due
      - total_balance_due
      - total_bill_unpaid_amount
      - total_unpaid_interest_amount
      - total_unpaid_penalty_amount
      - total_unpaid_principal_amount
      type: object
      properties:
        total_unpaid_penalty_amount:
          type: number
          description: Total unpaid penalty amount of all items in all bills
        total_unpaid_interest_amount:
          type: number
          description: Total unpaid interest amount of all items in all bills
        total_unpaid_principal_amount:
          type: number
          description: Total unpaid principal amount of all items in all bills
        total_bill_unpaid_amount:
          type: number
          description: Total unpaid amount of all items in all bills
        total_balance_due:
          type: number
          description: Total unpaid balance of all items in all bills
        minimum_payment_due:
          type: number
          description: Total minimum payment due of all items in all bills
      description: Bill element of the account
    InstallmentBills1:
      title: InstallmentBills1
      required:
      - total_bill_unpaid_amount
      - unpaid_interest_amount
      - unpaid_penalty_amount
      - unpaid_principal_amount
      type: object
      properties:
        unpaid_penalty_amount:
          type: number
          description: Unpaid penalty amount of all items in all installment bills
        unpaid_interest_amount:
          type: number
          description: Unpaid interest amount of all items in all installment bills
        unpaid_principal_amount:
          type: number
          description: Unpaid principal amount of all items in all installment bills
        total_bill_unpaid_amount:
          type: number
          description: Total unpaid amount of all items in all installment bills
      description: Installment bill element of the account
    MinimumPaymentBills1:
      title: MinimumPaymentBills1
      required:
      - full_payment_due
      - minimum_payment_due
      - principal_due
      - unpaid_interest_amount
      - unpaid_penalty_amount
      - unpaid_principal_amount
      type: object
      properties:
        unpaid_penalty_amount:
          type: number
          description: Unpaid penalty amount of all items in all minimum bills
        unpaid_interest_amount:
          type: number
          description: Unpaid interest amount of all items in all minimum bills
        unpaid_principal_amount:
          type: number
          description: Unpaid principal amount of all items in all minimum bills
        minimum_payment_due:
          type: number
          description: Minimum payment due of all items in all minimum bills
        principal_due:
          type: number
          description: Unpaid principal of all items in all minimum bills
        full_payment_due:
          type: number
          description: Full payment due of all items in all minimum bills
    AccountDetailsSuccess1:
      title: AccountDetailsSuccess1
      required:
      - rs_body
      type: object
      properties:
        rs_body:
          $ref: '#/components/schemas/RsBody2'
    LoanItemDetailsRequest:
      title: LoanItemDetailsRequest
      required:
      - rq_body
      type: object
      properties:
        rq_body:
          type: object
      example:
        rq_body: {}
    LoanAccountActivityRequest:
      title: LoanAccountActivityRequest
      required:
      - rq_body
      type: object
      properties:
        rq_body:
          type: object
      example:
        rq_body: {}
    LoanItemDetailsError3:
      title: LoanItemDetailsError3
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error2'
    LoanAccountActivitySuccess:
      title: LoanAccountActivitySuccess
      required:
      - rs_body
      type: object
      properties:
        rs_body:
          $ref: '#/components/schemas/RsBody6'
    RsBody6:
      title: RsBody6
      required:
      - transactions
      type: object
      properties:
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Transaction:
      title: Transaction
      required:
      - disbursement
      - end_balance
      - job_id
      - original_transaction_date
      - repayment
      - service_branch
      - transaction_amount
      - transaction_code
      - transaction_date
      - transaction_description
      - transaction_sequence
      - transaction_time
      - user_id
      type: object
      properties:
        transaction_sequence:
          type: integer
          description: Transaction sequence (running by account)
          format: int32
        transaction_date:
          type: string
          description: Transaction date
        transaction_time:
          type: string
          description: Transaction time
        transaction_code:
          type: string
          description: Indicate business type of transaction
        transaction_description:
          type: string
          description: Transaction description
        original_transaction_date:
          type: string
          description: Original transaction date
        transaction_amount:
          type: number
          description: Transaction amount
        end_balance:
          type: number
          description: Balance after transaction
        user_id:
          type: string
          description: ID of user who perform transaction
        service_branch:
          type: integer
          description: Branch where transaction is performed
          format: int32
        job_id:
          type: string
          description: Unique ID of transaction
        disbursement:
          $ref: '#/components/schemas/Disbursement'
        repayment:
          $ref: '#/components/schemas/Repayment'
    Disbursement:
      title: Disbursement
      required:
      - account_sequence
      - first_payment_date
      - installment_amount
      - interest_index
      - interest_rate
      - interest_spread
      - number_of_payment
      - original_job_id
      - original_transaction_sequence
      - related_account
      type: object
      properties:
        account_sequence:
          type: integer
          description: Loan account item
          format: int32
        installment_amount:
          type: number
          description: Amount of money expected to be paid in each time period
        first_payment_date:
          type: string
          description: The first date to perform repayment transaction. Display in format "YYYY-MM-DD"
        number_of_payment:
          type: integer
          description: The number of time period that customer have to repay for this item
          format: int32
        interest_index:
          type: string
          description: A benchmark to calculate the interest rate that is charged on financial products
        interest_spread:
          type: number
          description: A profit margin to bank, which is the difference between the interest rate a bank pays to depositors and the interest rate it receives from loans to consumers
        interest_rate:
          type: number
          description: Rate used to calculation interest amount
        related_account:
          type: string
          description: Linked deposit account number
        original_job_id:
          type: string
          description: Original unique ID (only reverse/adjust transaction)
        original_transaction_sequence:
          type: integer
          description: Original transaction sequence of reversed transaction (only reverse/adjust transaction)
          format: int32
      description: Disbursement transaction information
    Repayment:
      title: Repayment
      required:
      - interest_amount
      - original_job_id
      - penalty_amount
      - principal_amount
      - related_account
      type: object
      properties:
        principal_amount:
          type: integer
          description: Allocated principal amount
          format: int32
        interest_amount:
          type: number
          description: Allocated interest amount
        penalty_amount:
          type: number
          description: Allocated penalty amount
        related_account:
          type: string
          description: Linked deposit account number
        original_job_id:
          type: string
          description: Original unique ID (only adjust transaction)
      description: Repayment transaction information
    LoanAccountActivityFail:
      title: LoanAccountActivityFail
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          description: List of errors
          items:
            $ref: '#/components/schemas/Error'
