---
openapi: 3.0.0
info:
  title: Backoffice Service
  contact: {}
  version: "1.0"
servers:
  - url: http://127.0.0.1
tags:
  - name: Transaction Adjustment
paths:
  /dloan-transaction/v1/transactions/adjustment:
    post:
      tags:
        - Transaction Adjustment
      summary: Transaction Reversal
      operationId: TransactionReversal
      parameters:
        - name: x-request-id
          in: header
          description: Generated with RFC4122 standard.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-job-id
          in: header
          description: 'Generated by target service if blank, if not blank, use existing. Format: {XX}_{YYMMDD}{AAAAAAAA}{BB}{CCCCCC} 22 Digits created based on combination of : - {XX} : Domain Number - {YYYYYY} : 6 digits of YYMMDD - {AAAAAAAA} : 8 characters, created from timestamp hashed with CRC32 Example : 2017-10-10T14:45:27.201131865+07:00  -> 958fd1cb - {BB} : 2 digits of Domain Code (01) - {CCCCCC} : 6 digits of secure random (067492)'
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-real-ip
          in: header
          description: IP of caller
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 127.0.0.1
        - name: x-caller-service
          in: header
          description: Caller Service
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: FrontEnd
        - name: x-caller-domain
          in: header
          description: Caller Domain
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: Front
        - name: datetime
          in: header
          description: Date and time of request
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 2019-07-04T00:00:00+07:00
        - name: accept
          in: header
          description: Example “application/json”
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: application/json
        - name: accept-language
          in: header
          description: Accept language (e.g en/th)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: accept-encoding
          in: header
          description: Character encoding (UTF-8)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-device
          in: header
          description: Client Device
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-application
          in: header
          description: Application that sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-channel
          in: header
          description: Channel used to sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: user-agent
          in: header
          description: Browser agent/mobile/etc (HTTP standard header)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: client_id
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 10400cc592254e2e0a7a863cf1090c91a1c14dd745e20d9924abc7fd9dd9b303d71e
        - name: original-caller-domain
          in: header
          description: Original caller domain
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int32
            example: 88
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionReversalRequest'
            example:
              rq_body:
                account_number: 1000000001
                account_sequence: 1
                adjust_principal_with_ica_info:
                  clearing_and_settlement_key: MIDWAYITSA
                  transaction_amount: 1000
                adjust_int_accr:
                  transaction_amount: 1000
                adjust_pen_accr:
                  transaction_amount: 1000
                user_id: checker ID
                application_id: txn
                event: disbursement
                comment: adj-by-reverse-disbursement
                effective_date: 2021-03-15T00:00:00.000+0000
                service_branch: 828
                terminal_id: "1"
                other_prop: {}
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
              example:
                rs_body: {}
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failed1'
              example:
                errors:
                  - error_code: E88020512
                    error_type: BUSINESS
                    error_desc: Effective date must be equal or less than to system date
                    error_detail: Effective date must be equal or less than to system date
      deprecated: false
  /dloan-interest/v1/transactions/waive-penalty:
    post:
      tags:
        - Transaction Adjustment
      summary: Waive Penalty
      operationId: WaivePenalty
      parameters:
        - name: x-request-id
          in: header
          description: Generated with RFC4122 standard.
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-job-id
          in: header
          description: 'Generated by target service if blank, if not blank, use existing. Format: {XX}_{YYMMDD}{AAAAAAAA}{BB}{CCCCCC} 22 Digits created based on combination of : - {XX} : Domain Number - {YYYYYY} : 6 digits of YYMMDD - {AAAAAAAA} : 8 characters, created from timestamp hashed with CRC32 Example : 2017-10-10T14:45:27.201131865+07:00  -> 958fd1cb - {BB} : 2 digits of Domain Code (01) - {CCCCCC} : 6 digits of secure random (067492)'
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: e870d4c8-57a7-4796-923b-3965401b6ede
        - name: x-real-ip
          in: header
          description: IP of caller
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 127.0.0.1
        - name: x-caller-service
          in: header
          description: Caller Service
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: FrontEnd
        - name: x-caller-domain
          in: header
          description: Caller Domain
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: Front
        - name: datetime
          in: header
          description: Date and time of request
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 2019-07-04T00:00:00+07:00
        - name: accept
          in: header
          description: Example “application/json”
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: application/json
        - name: accept-language
          in: header
          description: Accept language (e.g en/th)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: accept-encoding
          in: header
          description: Character encoding (UTF-8)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-device
          in: header
          description: Client Device
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-application
          in: header
          description: Application that sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: x-channel
          in: header
          description: Channel used to sent the request
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: user-agent
          in: header
          description: Browser agent/mobile/etc (HTTP standard header)
          required: false
          style: simple
          explode: false
          schema:
            type: string
        - name: client_id
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: 10400cc592254e2e0a7a863cf1090c91a1c14dd745e20d9924abc7fd9dd9b303d71e
        - name: original-caller-domain
          in: header
          description: Original caller domain
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int32
            example: 88
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WaivePenaltyRequest'
            example:
              rq_body:
                account_number: 1000000001
                penalty_amount: 1000
                oldest_stmt_due_date: 2021-03-14T00:00:00.000+0000
                is_start_penalty: true
                user_id: checker ID
                comment: comment
                effective_date: 9999-03-15T00:00:00.000+0000
                service_branch: 828
                terminal_id: "1"
                other_prop: {}
        required: true
      responses:
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Failed1'
              example:
                errors:
                  - error_code: E88020512
                    error_type: BUSINESS
                    error_desc: Effective date must be equal or less than to system date
                    error_detail: Effective date must be equal or less than to system date
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Success'
              example:
                rs_body: {}
      deprecated: false
components:
  schemas:
    TransactionReversalRequest:
      title: TransactionReversalRequest
      required:
        - rq_body
      type: object
      properties:
        rq_body:
          $ref: '#/components/schemas/RqBody'
    RqBody:
      title: RqBody
      required:
        - account_number
        - account_sequence
        - adjust_int_accr
        - adjust_pen_accr
        - adjust_principal_with_ica_info
        - application_id
        - effective_date
        - event
        - service_branch
        - user_id
      type: object
      properties:
        account_number:
          type: integer
          description: Loan account number
          format: int32
        account_sequence:
          type: integer
          description: Loan account item
          format: int32
        adjust_principal_with_ica_info:
          $ref: '#/components/schemas/AdjustPrincipalWithIcaInfo'
        adjust_int_accr:
          $ref: '#/components/schemas/AdjustIntAccr'
        adjust_pen_accr:
          $ref: '#/components/schemas/AdjustPenAccr'
        user_id:
          type: string
        application_id:
          type: string
        event:
          type: string
        comment:
          type: string
        effective_date:
          type: string
        service_branch:
          type: integer
          format: int32
        terminal_id:
          type: string
        other_prop:
          type: object
    AdjustPrincipalWithIcaInfo:
      title: AdjustPrincipalWithIcaInfo
      required:
        - clearing_and_settlement_key
      type: object
      properties:
        clearing_and_settlement_key:
          type: string
          description: Indicate the system/unit where the transaction is involved, used for mapping GL configuration for settlement and accounting process
        transaction_amount:
          type: number
          description: Principal amount to be adjusted, by increasing (+), decreasing (-), or adjust nothing (null)
      description: Principal adjustment information
    AdjustIntAccr:
      title: AdjustIntAccr
      type: object
      properties:
        transaction_amount:
          type: number
          description: Interest amount to be adjusted, by increasing (+), decreasing (-), or adjust nothing (null)
      description: Interest adjustment information
    AdjustPenAccr:
      title: AdjustPenAccr
      type: object
      properties:
        transaction_amount:
          type: number
          description: Penalty amount to be adjusted, by increasing (+), decreasing (-), or adjust nothing (null)
      description: Penalty adjustment information
    Success:
      title: Success
      required:
        - rs_body
      type: object
      properties:
        rs_body:
          type: object
    Error:
      title: Error
      required:
        - error_code
        - error_desc
        - error_detail
        - error_type
      type: object
      properties:
        error_code:
          type: string
          description: Error code
        error_type:
          type: string
          description: Type of error
        error_desc:
          type: string
          description: Error description
      description: List of errors
    Failed1:
      title: Failed1
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    WaivePenaltyRequest:
      title: WaivePenaltyRequest
      required:
        - rq_body
      type: object
      properties:
        rq_body:
          $ref: '#/components/schemas/RqBody1'
    RqBody1:
      title: RqBody1
      required:
        - account_number
        - effective_date
        - is_start_penalty
        - oldest_stmt_due_date
        - service_branch
        - user_id
      type: object
      properties:
        account_number:
          type: integer
          description: Loan account number
          format: int32
        penalty_amount:
          type: number
          description: Penalty amount to be waived
        oldest_stmt_due_date:
          type: string
          description: The oldest due date of unpaid statement of all items under the account
        is_start_penalty:
          type: boolean
          description: Flag to indicate whether the account already started calculate penalty
        user_id:
          type: string
          description: ID of user who perform reverse/adjust transaction
        comment:
          type: string
          description: Comment
        effective_date:
          type: string
          description: Effective date. Display in format "YYYY-MM-DD". Usually be system date
        service_branch:
          type: integer
          description: Branch where penalty is waived
          format: int32
        terminal_id:
          type: string
          description: Terminal location
        other_prop:
          type: object
          description: Other properties involved with the transaction. Able to input any fields/values inside
