---
openapi: 3.0.0
info:
  title: Lending Product Set Up
  description: |-
    - Interest Plan
    - Penalty Plan
    - Payment Plan
  contact: {}
  version: "1.0"
servers:
- url: http://example.com
tags:
- name: Create/Update Product
paths:
  /dloan-interest/v1/plan/update-interest-plan:
    post:
      tags:
      - Create/Update Product
      summary: Interest Plan
      description: Update Interest Plan
      operationId: InterestPlan
      parameters:
      - name: x-request-id
        in: header
        description: Generated with RFC4122 standard
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: e870d4c8-57a7-4796-923b-3965401b6ede
      - name: x-job-id
        in: header
        description: 'Generated by target service if blank, if not blank, use existing. Format: {XX}_{YYMMDD}{AAAAAAAA}{BB}{CCCCCC} 22 Digits created based on combination of : - {XX} : Domain Number - {YYYYYY} : 6 digits of YYMMDD - {AAAAAAAA} : 8 characters, created from timestamp hashed with CRC32 Example : 2017-10-10T14:45:27.201131865+07:00  -> 958fd1cb - {BB} : 2 digits of Domain Code (01) - {CCCCCC} : 6 digits of secure random (067492)'
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: e870d4c8-57a7-4796-923b-3965401b6ede
      - name: x-real-ip
        in: header
        description: Retrieving data. Wait a few seconds and try to cut or copy again.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 127.0.0.1
      - name: x-caller-service
        in: header
        description: Caller Service
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: FrontEnd
      - name: x-caller-domain
        in: header
        description: Caller Domain
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Front
      - name: x-device
        in: header
        description: Client Device
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-application
        in: header
        description: Application that sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-channel
        in: header
        description: Channel used to sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: user-agent
        in: header
        description: Browser agent/mobile/etc (HTTP standard header)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: datetime
        in: header
        description: Date and time of request
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 2021-03-15T10:46:46.836+0000
      - name: accept
        in: header
        description: Example “application/json”
        required: false
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: accept-language
        in: header
        description: Accept language (e.g en/th)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: accept-encoding
        in: header
        description: Character encoding (UTF-8)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: original-caller-domain
        in: header
        description: Original caller domain
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InterestPlanRequest'
            example:
              rq_body:
                name: interest01
                description: Revolving Interest rate
                interest_index: MRR
                interest_spread: 13.88
                maximum_rate_index: MAX
        required: true
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterestPlanFail1'
              example:
                errors:
                - error_code: E88020511
                  error_type: BUSINESS
                  error_desc: Can not update interest plan
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InterestPlanSuccess'
              example:
                rs_body: {}
      deprecated: false
  /dloan-interest/v1/plan/update-penalty-plan:
    post:
      tags:
      - Create/Update Product
      summary: Penalty Plan
      description: Update Penalty Plan
      operationId: PenaltyPlan
      parameters:
      - name: x-request-id
        in: header
        description: Generated with RFC4122 standard
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: e870d4c8-57a7-4796-923b-3965401b6ede
      - name: x-job-id
        in: header
        description: 'Generated by target service if blank, if not blank, use existing. Format: {XX}_{YYMMDD}{AAAAAAAA}{BB}{CCCCCC} 22 Digits created based on combination of : - {XX} : Domain Number - {YYYYYY} : 6 digits of YYMMDD - {AAAAAAAA} : 8 characters, created from timestamp hashed with CRC32 Example : 2017-10-10T14:45:27.201131865+07:00  -> 958fd1cb - {BB} : 2 digits of Domain Code (01) - {CCCCCC} : 6 digits of secure random (067492)'
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: e870d4c8-57a7-4796-923b-3965401b6ede
      - name: x-real-ip
        in: header
        description: IP of caller
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 127.0.0.1
      - name: x-caller-service
        in: header
        description: Caller Service
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: FrontEnd
      - name: x-caller-domain
        in: header
        description: Caller Domain
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Front
      - name: x-device
        in: header
        description: Client Device
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-application
        in: header
        description: Application that sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-channel
        in: header
        description: Channel used to sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: user-agent
        in: header
        description: Browser agent/mobile/etc (HTTP standard header)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: datetime
        in: header
        description: Date and time of request
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 2021-03-15T10:46:46.836+0000
      - name: accept
        in: header
        description: Example “application/json”
        required: false
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: accept-language
        in: header
        description: Accept language (e.g en/th)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: accept-encoding
        in: header
        description: Character encoding (UTF-8)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: original-caller-domain
        in: header
        description: Original caller domain
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PenaltyPlanRequest'
            example:
              rq_body:
                name: penalty03
                description: BOT penalty requirement
                interest_index: PEN
                installment_penalty_cal_base: prin-due
                minimum_penalty_cal_base: prin-bal
                penalty_cal_method: penalty-spread
                penalty_spread: 3
        required: true
      responses:
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PenaltyPlanFailed1'
              example:
                errors:
                - error_code: E88020511
                  error_type: BUSINESS
                  error_desc: Can not update penalty plan
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PenaltyPlanSuccess'
              example:
                rs_body: {}
      deprecated: false
  /dloan-payment/v1/plan/update-payment-plan:
    post:
      tags:
      - Create/Update Product
      summary: Payment Plan
      description: Update Payment Plan
      operationId: PaymentPlan
      parameters:
      - name: x-request-id
        in: header
        description: Generated with RFC4122 standard
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: e870d4c8-57a7-4796-923b-3965401b6ede
      - name: x-job-id
        in: header
        description: 'Generated by target service if blank, if not blank, use existing. Format: {XX}_{YYMMDD}{AAAAAAAA}{BB}{CCCCCC} 22 Digits created based on combination of : - {XX} : Domain Number - {YYYYYY} : 6 digits of YYMMDD - {AAAAAAAA} : 8 characters, created from timestamp hashed with CRC32 Example : 2017-10-10T14:45:27.201131865+07:00  -> 958fd1cb - {BB} : 2 digits of Domain Code (01) - {CCCCCC} : 6 digits of secure random (067492)'
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: e870d4c8-57a7-4796-923b-3965401b6ede
      - name: x-real-ip
        in: header
        description: IP of caller
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 127.0.0.1
      - name: x-caller-service
        in: header
        description: Caller Service
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: FrontEnd
      - name: x-caller-domain
        in: header
        description: Caller Domain
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Front
      - name: x-device
        in: header
        description: Client Device
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-application
        in: header
        description: Application that sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: x-channel
        in: header
        description: Channel used to sent the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: user-agent
        in: header
        description: Browser agent/mobile/etc (HTTP standard header)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: datetime
        in: header
        description: Date and time of request
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: 2021-03-15T10:46:46.836+0000
      - name: accept
        in: header
        description: Example “application/json”
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: application/json
      - name: accept-language
        in: header
        description: Accept language (e.g en/th)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: accept-encoding
        in: header
        description: Character encoding (UTF-8)
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: original-caller-domain
        in: header
        description: Original caller domain
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentPlanRequest'
            example:
              rq_body:
                name: payment01
                description: Able to advance payment and last installment bill option is installment
                payment_frequency: 1
                payment_unit: M
                payment_date: 31
                payment_calculation_method: installment+penalty
                last_installment_bill_option: installment-amount
                billing_offset_day: 1
                is_advance_during_billing_offset: true
                is_advance_on_due_date: false
                is_advance_after_due_date: true
                minimum_principal_payment_amount: 300
                minimum_principal_payment_percentage: 5
                last_disb_date_for_current_payment_period: 15
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentPlanSuccess'
              example:
                rs_body: {}
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentPlanFail1'
              example:
                errors:
                - error_code: E88020511
                  error_type: BUSINESS
                  error_desc: Can not update payment plan
      deprecated: false
components:
  schemas:
    InterestPlanRequest:
      title: InterestPlanRequest
      required:
      - rq_body
      type: object
      properties:
        rq_body:
          $ref: '#/components/schemas/RqBody'
    RqBody:
      title: RqBody
      required:
      - description
      - interest_index
      - interest_spread
      - maximum_rate_index
      - name
      type: object
      properties:
        name:
          type: string
          description: Interest plan name
        description:
          type: string
          description: Interest plan description
        interest_index:
          type: string
          description: A benchmark to calculate the interest rate that is charged on financial products
        interest_spread:
          type: number
          description: A profit margin to bank, which is the difference between the interest rate a bank pays to depositors and the interest rate it receives from loans to consumers
        maximum_rate_index:
          type: string
          description: A max benchmark to calculate the rate that is charged on financial products
    Error:
      title: Error
      required:
      - error_code
      - error_desc
      - error_type
      type: object
      properties:
        error_code:
          type: string
          description: Error code
        error_type:
          type: string
          description: Type of error
        error_desc:
          type: string
          description: Error description
      description: List of errors
    InterestPlanFail1:
      title: InterestPlanFail1
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    InterestPlanSuccess:
      title: InterestPlanSuccess
      required:
      - rs_body
      type: object
      properties:
        rs_body:
          type: object
    PenaltyPlanRequest:
      title: PenaltyPlanRequest
      required:
      - rq_body
      type: object
      properties:
        rq_body:
          $ref: '#/components/schemas/RqBody1'
    RqBody1:
      title: RqBody1
      required:
      - description
      - installment_penalty_cal_base
      - minimum_penalty_cal_base
      - name
      - penalty_cal_method
      - penalty_index
      - penalty_spread
      type: object
      properties:
        name:
          type: string
          description: Penalty plan name
        description:
          type: string
          description: Penalty plan description
        penalty_index:
          type: string
          description: A benchmark to calculate the penalty rate that is charged on financial products
        installment_penalty_cal_base:
          type: string
          description: Method used to calculate penalty if payment_calculation_method is installment
        minimum_penalty_cal_base:
          type: string
          description: Method used to calculate penalty if payment_calculation_method is minimum
        penalty_cal_method:
          type: string
          description: Penalty calculation method
        penalty_spread:
          type: number
          description: A margin between penalty calculation rate and normal interest rate
    PenaltyPlanFailed1:
      title: PenaltyPlanFailed1
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    PenaltyPlanSuccess:
      title: PenaltyPlanSuccess
      required:
      - rs_body
      type: object
      properties:
        rs_body:
          type: object
    PaymentPlanRequest:
      title: PaymentPlanRequest
      required:
      - rq_body
      type: object
      properties:
        rq_body:
          $ref: '#/components/schemas/RqBody2'
    RqBody2:
      title: RqBody2
      required:
      - billing_offset_day
      - description
      - is_advance_after_due_date
      - is_advance_during_billing_offset
      - is_advance_on_due_date
      - last_disb_date_for_current_payment_period
      - last_installment_bill_option
      - minimum_principal_payment_amount
      - minimum_principal_payment_percentage
      - name
      - payment_calculation_method
      - payment_date
      - payment_frequency
      - payment_unit
      type: object
      properties:
        name:
          type: string
          description: Payment plan name
        description:
          type: string
          description: Payment plan description
        payment_frequency:
          type: integer
          description: Frequency of invoice period
          format: int32
        payment_unit:
          type: string
          description: Time unit of invoice period. Display in abbreviation e.g. M (month), W (week)
        payment_date:
          type: integer
          description: Specified date in month to perform repayment transaction
          format: int32
        payment_calculation_method:
          type: string
          description: 'Name of method used to calculate payment '
        last_installment_bill_option:
          type: string
          description: Method used to calculate last bill if payment_calculation_method is installment
        billing_offset_day:
          type: integer
          description: Number of days between cut off date and bill generation date
          format: int32
        is_advance_during_billing_offset:
          type: boolean
          description: Flag to indicate whether advance payment is allowed during billing offset period
        is_advance_on_due_date:
          type: boolean
          description: Flag to indicate whether advance payment is allowed on due date
        is_advance_after_due_date:
          type: boolean
          description: Flag to indicate whether advance payment is allowed after due date
        minimum_principal_payment_amount:
          type: number
          description: Principal amount paid, used if payment_calculation_method is minimum
        minimum_principal_payment_percentage:
          type: number
          description: Principal percentage paid, used if payment_calculation_method is minimum
        last_disb_date_for_current_payment_period:
          type: integer
          description: Last date to perform disbursement whose first payment is included in current payment period's bill. If performing disbursement after the specified date, the first payment will be included in the next payment period's bill
          format: int32
    PaymentPlanSuccess:
      title: PaymentPlanSuccess
      required:
      - rs_body
      type: object
      properties:
        rs_body:
          type: object
    PaymentPlanFail1:
      title: PaymentPlanFail1
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
